### ISSUE TITLE
Feature Request - Apple Watch app/complication support

### ISSUE THREAD

**Issue by oven-lab** [eclair4151/MC-Status-Widget-for-Minecraft#26] opened 2021-08-08 18:48 UTC
Hi!

This is not an issue, but a feature request!

It would be awesome to get a notification when the app detects when a server is offline. Do not need to be super fancy with a server constantly checking, but while the app checks in the background (or whenever it checks) it could send a notification if a server is offline.

Also a watch kit app would be great!

**Comment by eclair4151** [comment] 2021-08-08 19:11
Watch kit app is on the todo list 😊. For you first item, please view the app > info page > FAQ

**Comment by freepicheep** [comment] 2023-05-18 20:09
@eclair4151 Just curious if you are still planning on implementing this feature. I would be interested in working on it if it's not something you are going to do.

**Comment by eclair4151** [comment] 2023-05-18 20:16
Hey, yea that would be great, ill take any help I can get. I haven't had much time to play with it, so if you want to pick up from the last commit in main, that's where I left off. Any help is super appreciated!

**Comment by freepicheep** [comment] 2023-05-18 20:35
Okay, I'll take a look at it and see what I can do! I never did anything with UIKit...just SwiftUI so it might take me a bit to get familiar with the project. I'll let you know if I have any questions.

**Comment by eclair4151** [comment] 2023-05-18 20:36
Sounds good! The watch should be in 100% swift ui and doesnt support UIKit at all, so that should be fine.

**Comment by freepicheep** [comment] 2023-05-20 20:51
I'm getting a lot of errors when I try to run the project. Would you mind checking to see if everything compiles for you? I'm not sure if some of the dependencies need updated or what exactly the problem is.

**Comment by eclair4151** [comment] 2023-05-29 12:26
Yea honestly, I wouldnt really even bother with this right now for the watch thinking about it. I have a bigger re write in mind anyway which will remove all third party libs so a large portion is going to change and would need a re write. Better until to wait un til I update this old code first, which I think will also help the build process, which is usually f'ed up because of realm which I regret ever using. I also want to remove the entire socket lib, now that one in swift exists naively, which didnt when I made this app.

**Comment by eclair4151** [comment] 2023-08-16 14:17
Just as an update, the watch app is being worked on now as part of my iOS 17 rewrite, and should be released in September.

**Comment by eclair4151** [comment] 2024-10-18 23:20
This is now complete. You can test the new 2.0 version of the app here on testflight before release:

WARNING!! There is currently a bug that means you will have to delete and re-add your widgets if you try out the new beta. This should be resolved before release but I didnt want to hold up testing.

https://testflight.apple.com/join/UqHNAYJn

**Closed by eclair4151** 2024-10-18 23:20 UTC
Labels: enhancement
