### ISSUE TITLE
Not working for NeoProtect servers

### ISSUE THREAD

**Issue by manuelmayer-dev** [eclair4151/MC-Status-Widget-for-Minecraft#42] opened 2024-11-17 21:36 UTC
The latest version does no longer work with servers that are protected by NeoProtect. An example to test would be play.SGHub.eu

![image](https://github.com/user-attachments/assets/f53f497d-09f4-48b6-b2d2-df86de139ea1)

other apps and the previous version (before the redesign) work.
![image](https://github.com/user-attachments/assets/c000754f-a0ac-4b12-a2ea-bf56ffe4b903)

**Comment by eclair4151** [comment] 2024-11-17 23:44
Im not sure the exact reason for this, but I have fixed it with a temporary workaround, which will be released in 2.0.2 tomorrow.

**Closed by eclair4151** 2024-11-17 23:44 UTC

**Comment by eclair4151** [comment] 2024-11-18 17:01
@manuelmayer-dev Version 2.0.2 is now out on the appstore and should fix this issue. Can you try it out and confirm the issue is fixed? If so I would also greatly appreciate if the issue is fixed, if you could potentially update your review on the appstore as well :) 

![IMG_2659](https://github.com/user-attachments/assets/8b54ba7c-774d-4c43-b560-5fda3cadfb64)

**Comment by manuelmayer-dev** [comment] 2024-11-18 17:57
Sure, it works flawlessly now.
